import test from 'node:test';
import assert from 'node:assert/strict';
import {seedState} from '../lib/model.ts';
import {initialChats,chatsFor,applyChatProposal,prepareReply} from '../lib/assistant-chat.ts';
import {sidebarSwipeDirection,completesSidebarSwipe} from '../lib/sidebar-swipe.ts';
const at='2026-09-24T12:00:00Z';
function setup(index){const data=seedState();data.chats=initialChats(data);const chat=data.chats[index];const message=chat.messages[1];return {data,chat,message};}
function apply(f,input=f.message.proposal,id='test-action'){return applyChatProposal(f.data,f.chat.id,f.message.id,input,id,at);}
test('reviewed reminder is linked, persistent in chat and cannot be applied twice',()=>{const f=setup(0);const before=JSON.stringify(f.data);const result=apply(f);assert.equal(result.error,undefined);assert.equal(JSON.stringify(f.data),before);assert.equal(result.data.tasks.length,f.data.tasks.length+1);assert.equal(result.data.tasks[0].contactId,f.message.proposal.contactId);assert.ok(chatsFor(result.data)[0].messages[1].receipt);const repeated=apply({...f,data:result.data});assert.ok(repeated.error);assert.equal(repeated.data,result.data);});
test('matching reminder is reused instead of duplicated',()=>{const f=setup(0);const input=f.message.proposal;f.data.tasks.push({id:'existing',contactId:input.contactId,title:input.title,priority:'Closing',due:input.date,time:input.time,done:false});const result=apply(f);assert.equal(result.data.tasks.length,f.data.tasks.length);assert.match(chatsFor(result.data)[0].messages[1].receipt.text,/No duplicate/);});
test('owner draft enters review queue without sending or changing the owner',()=>{const f=setup(1);const result=apply(f,{...f.message.proposal,body:'Edited personal follow-up'});assert.equal(result.data.approvals[0].status,'Pending');assert.equal(result.data.approvals[0].message,'Edited personal follow-up');assert.deepEqual(result.data.contacts,f.data.contacts);assert.deepEqual(result.data.campaigns,f.data.campaigns);});
test('launch action creates an unsent campaign with unverified facts',()=>{const f=setup(2);const result=apply(f);assert.equal(result.data.campaigns[0].status,'Draft');assert.deepEqual(result.data.campaigns[0].recipients,[]);assert.equal(result.data.campaigns[0].price,'To be confirmed');});
test('contact opted out after preparation blocks action',()=>{const f=setup(1);f.data.contacts.find(c=>c.id===f.message.proposal.contactId).optOut=true;const result=apply(f);assert.match(result.error,/do not contact/);assert.equal(result.data,f.data);});
test('missing contact, changed context and dismissed proposals cannot modify records',()=>{const f=setup(0);assert.ok(apply(f,{...f.message.proposal,contactId:'c5'}).error);f.message.dismissed=true;assert.ok(apply(f).error);delete f.message.dismissed;f.data.contacts=f.data.contacts.filter(c=>c.id!==f.message.proposal.contactId);assert.ok(apply(f).error);});
test('blank drafts and invalid reminder dates are rejected',()=>{const f=setup(0);for(const patch of [{title:''},{date:'2026-02-30'},{date:'invalid'},{time:'25:99'}])assert.ok(apply(f,{...f.message.proposal,...patch}).error);});
test('unknown questions honestly explain the demo, without inventing actions',()=>{const reply=prepareReply('Who won the football match?',seedState(),'x');assert.equal(reply.proposal,undefined);assert.match(reply.text,/no live AI/);});
test('mobile swipe requires deliberate rightward movement, ignoring vertical and left gestures',()=>{assert.equal(sidebarSwipeDirection(8,40),'cancel');assert.equal(sidebarSwipeDirection(-40,2),'cancel');assert.equal(sidebarSwipeDirection(30,4),'right');assert.equal(completesSidebarSwipe(80,10),true);assert.equal(completesSidebarSwipe(70,10),false);assert.equal(completesSidebarSwipe(80,60),false);});
