'use client';
import {useState} from 'react';
import {Building2,Phone,Plus,Pencil,CalendarDays,Sparkles,Pause,Play,ArrowUpRight,MessageSquare} from 'lucide-react';
import {Sheet,SheetContent,SheetHeader,SheetTitle,SheetDescription} from '@/components/ui/sheet';
import {Button} from '@/components/ui/button';
import {Textarea} from '@/components/ui/textarea';
import {Card,CardContent} from '@/components/ui/card';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {useCRM} from '@/components/crm-provider';
import {Avatar,CheckButton,Empty,Field,Picker,Pill,PriorityPill,SectionTitle} from '@/components/crm-ui';
import {ContactForm,DealForm,TaskForm} from '@/components/forms';
import {OWNER_STAGES,money,uid} from '@/lib/model';
export function ContactDetail({id,onClose,onDeal}:{id:string;onClose:()=>void;onDeal:(id:string)=>void}){
 const{data,setData,notify,log}=useCRM();const[editing,setEditing]=useState(false);const[task,setTask]=useState(false);const[note,setNote]=useState('');const[tab,setTab]=useState('overview');const c=data.contacts.find(c=>c.id===id);
 if(!c)return <Sheet open onOpenChange={v=>!v&&onClose()}><SheetContent><SheetHeader><SheetTitle>Contact not found</SheetTitle><SheetDescription>This record may have been reset in this browser.</SheetDescription></SheetHeader></SheetContent></Sheet>;
 function addNote(kind:'note'|'call'='note'){if(!note.trim()||!c)return;const text=note.trim();setData(s=>({...s,contacts:s.contacts.map(x=>x.id===c.id?{...x,notes:[{id:uid(),text,at:new Date().toISOString()},...x.notes]}:x),activities:[{id:uid(),contactId:c.id,text:`${kind==='call'?'Call logged':'Note added'}: ${text}`,kind,at:new Date().toISOString()},...s.activities]}));setNote('');notify(kind==='call'?'Call note saved':'Note saved');}
 function signal(){if(!c||c.optOut)return;setData(s=>({...s,contacts:s.contacts.map(x=>x.id===c.id?{...x,ownerStage:'Engaged',priority:x.priority==='Closing'?'Closing':'Listing',signal:'Requested a valuation · simulated reply',nurture:'Paused',nextAction:'Call to agree a valuation appointment'}:x),approvals:s.approvals.some(a=>a.contactId===c.id&&a.kind==='handoff'&&a.status==='Pending')?s.approvals:[{id:uid(),contactId:c.id,kind:'handoff',title:`${c.name.split(' ')[0]} requested a valuation`,reason:'Simulated owner reply. Nurture is paused for a personal conversation.',message:`${c.name} is interested in a valuation for ${c.building}. Confirm the property details and schedule a call.`,status:'Pending'},...s.approvals],activities:[{id:uid(),contactId:c.id,text:'Simulated valuation request received. Nurture paused; handoff added to approvals.',kind:'assistant',at:new Date().toISOString()},...s.activities]}));notify('Owner engaged · assistant handoff created');}
 const deals=data.deals.filter(d=>d.contactId===id);const activities=data.activities.filter(a=>a.contactId===id);return <><Sheet open onOpenChange={v=>!v&&onClose()}><SheetContent className="detail-sheet"><SheetHeader><div className="contact-hero"><Avatar name={c.name}/><div><SheetTitle>{c.name}</SheetTitle><SheetDescription>{c.role} · {c.source}</SheetDescription></div></div><div className="flex flex-wrap gap-2"><PriorityPill priority={c.priority}/>{c.optOut&&<Pill tone="closing">Do not contact</Pill>}<Pill>Demo contact</Pill></div></SheetHeader><div className="detail-body"><div className="detail-actionbar"><Button variant="outline" onClick={()=>setEditing(true)}><Pencil/>Edit</Button><Button variant="outline" onClick={()=>setTask(true)}><CalendarDays/>Add reminder</Button><Button variant="outline" onClick={()=>setTab('notes')}><Phone/>Log call</Button></div><div className="context-highlight"><span className="eyebrow">NEXT ACTION</span><h3>{c.nextAction||'Choose the next step'}</h3><p>{c.signal}</p></div><Tabs value={tab} onValueChange={setTab}><TabsList variant="line" className="detail-tabs"><TabsTrigger value="overview">Overview</TabsTrigger><TabsTrigger value="notes">Notes ({c.notes.length})</TabsTrigger><TabsTrigger value="deals">Deals ({deals.length})</TabsTrigger><TabsTrigger value="activity">Activity</TabsTrigger></TabsList>
 <TabsContent value="overview" className="space-y-6"><div className="detail-fields"><Field label="Email"><p className="break-all">{c.email||'Not provided'}</p></Field><Field label="Phone"><p>{c.phone||'Not provided'}</p></Field><Field label="Area"><p>{c.area||'Not set'}</p></Field><Field label="Building"><p>{c.building||'Not set'}</p></Field><Field label="Budget / property value"><p>{money(c.budget)}</p></Field><Field label="Developer"><p>{c.developer||'Not set'}</p></Field></div>{c.role!=='Buyer'&&<><Field label="Owner pipeline stage"><Picker label="Change owner stage" value={c.ownerStage} options={OWNER_STAGES} onChange={v=>{setData(s=>({...s,contacts:s.contacts.map(x=>x.id===id?{...x,ownerStage:v,nurture:['Listing won','Lost'].includes(v)?'Off':x.nurture}:x)}));log(`Owner stage changed to ${v}.`,id);notify('Owner stage updated');}}/></Field><Card className="nurture-panel"><CardContent><SectionTitle title="Owner follow-up" icon={<Sparkles size={17}/>} aside={<Pill tone={c.nurture==='Active'?'nurture':'listing'}>{c.nurture}</Pill>}/><ol className="nurture-steps"><li><span>1</span>Introduction & selling timeline<small>Day 1</small></li><li><span>2</span>Building-level market insight<small>Day 4</small></li><li><span>3</span>Personal follow-up<small>Day 10</small></li><li><span>4</span>Agent handoff when interested<small>On reply</small></li></ol><p className="text-sm muted">Concept sequence. No automatic outreach runs in this demo.</p><div className="flex flex-wrap gap-2 mt-4"><Button variant="outline" disabled={c.optOut} onClick={()=>{const next=c.nurture==='Active'?'Paused':'Active';setData(s=>({...s,contacts:s.contacts.map(x=>x.id===id?{...x,nurture:next}:x)}));log(`Demo follow-up ${next.toLowerCase()}.`,id);notify(`Nurture ${next.toLowerCase()}`);}}>{c.nurture==='Active'?<Pause/>:<Play/>}{c.nurture==='Active'?'Pause sequence':'Activate demo sequence'}</Button><Button variant="secondary" disabled={c.optOut} onClick={signal}>Simulate valuation request</Button></div></CardContent></Card></>}</TabsContent>
 <TabsContent value="notes" className="space-y-5"><div className="note-composer"><Textarea aria-label="Contact note" value={note} onChange={e=>setNote(e.target.value)} placeholder="What did you learn? Capture the next step…"/><div><Button disabled={!note.trim()} variant="outline" onClick={()=>addNote('call')}><Phone/>Save call note</Button><Button disabled={!note.trim()} onClick={()=>addNote()}><Plus/>Add note</Button></div></div>{c.notes.map(n=><div className="note" key={n.id}><p>{n.text}</p><small>Walid · {new Date(n.at).toLocaleDateString('en-GB')}</small></div>)}</TabsContent>
 <TabsContent value="deals">{deals.length?deals.map(d=><Card key={d.id} className="mb-3"><CardContent><Button variant="link" className="text-link" onClick={()=>onDeal(d.id)}>{d.name}<ArrowUpRight/></Button><p className="muted text-sm mt-2">{d.property}</p><div className="flex justify-between mt-4"><strong>{money(d.value,true)}</strong><Pill>{d.stage}</Pill></div></CardContent></Card>):<Empty title="No deals yet" description="Create a deal from the Deals page and link this contact."/>}</TabsContent>
 <TabsContent value="activity">{activities.length?activities.map(a=><div className="activity-item" key={a.id}><span className="activity-icon">{a.kind==='assistant'?<Sparkles size={16}/>:a.kind==='call'?<Phone size={16}/>:<MessageSquare size={16}/>}</span><div><p>{a.text}</p><small>{new Date(a.at).toLocaleString('en-GB',{timeZone:'Asia/Dubai'})} GST</small></div></div>):<Empty title="A fresh relationship" description="Notes, calls and stage changes will appear here."/>}</TabsContent></Tabs></div></SheetContent></Sheet>{editing&&<ContactForm contact={c} onClose={()=>setEditing(false)}/ >}{task&&<TaskForm contactId={id} onClose={()=>setTask(false)}/ >}</>;
}
export function DealDetail({id,onClose,onContact}:{id:string;onClose:()=>void;onContact:(id:string)=>void}){const{data,setData,notify}=useCRM();const[editing,setEditing]=useState(false);const d=data.deals.find(d=>d.id===id);if(!d)return null;const c=data.contacts.find(c=>c.id===d.contactId);return <><Sheet open onOpenChange={v=>!v&&onClose()}><SheetContent className="detail-sheet"><SheetHeader><SheetTitle>{d.name}</SheetTitle><SheetDescription>{d.property}</SheetDescription></SheetHeader><div className="detail-body"><div className="deal-value"><strong>{money(d.value)}</strong><Pill tone={d.stage==='Closed won'?'nurture':'listing'}>{d.stage}</Pill></div><Button variant="outline" onClick={()=>setEditing(true)}><Pencil/>Edit deal</Button>{c&&<Button variant="ghost" className="person-cell" onClick={()=>onContact(c.id)}><Avatar name={c.name}/><span>{c.name}<small>{c.role}</small></span><ArrowUpRight/></Button>}<div className="context-highlight"><span className="eyebrow">NEXT STEP</span><h3>{d.nextAction||'No next step set'}</h3><p>Target closing · {d.closingDate}</p></div><div><SectionTitle title="Closing checklist" aside={<Pill>{d.checklist.filter(x=>x.done).length}/{d.checklist.length}</Pill>}/>{d.checklist.map((x,i)=><div className="checklist-row" key={x.label}><CheckButton checked={x.done} label={x.label} onClick={()=>{setData(s=>({...s,deals:s.deals.map(a=>a.id===id?{...a,checklist:a.checklist.map((b,j)=>j===i?{...b,done:!b.done}:b)}:a)}));notify('Checklist updated');}}/><span className={x.done?'line-through muted':''}>{x.label}</span></div>)}</div><Field label="Deal notes"><p className="leading-relaxed whitespace-pre-wrap">{d.notes||'No notes yet.'}</p></Field><div className="demo-note"><Building2 size={16}/>Property and transaction details are illustrative.</div></div></SheetContent></Sheet>{editing&&<DealForm deal={d} onClose={()=>setEditing(false)}/>}</>;}
