'use client';
import { FormEvent } from 'react';
import { Button } from '@/components/ui/button';
import { Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription } from '@/components/ui/dialog';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { useCRM } from '@/components/crm-provider';
import { Field,Picker } from '@/components/crm-ui';
import { Contact,Deal,Task,SOURCES,OWNER_STAGES,DEAL_STAGES,Priority,uid,today,shiftDate } from '@/lib/model';
const str=(f:FormData,key:string)=>(f.get(key)?.toString()||'').trim();
export function ContactForm({contact,owner=false,onClose,onSaved}:{contact?:Contact;owner?:boolean;onClose:()=>void;onSaved?:(id:string)=>void}){
 const {saveContact}=useCRM();
 function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const name=str(f,'name');if(!name)return;const role=str(f,'role') as Contact['role'];const c:Contact={id:contact?.id||uid(),name,email:str(f,'email'),phone:str(f,'phone'),role,source:str(f,'source'),area:str(f,'area'),building:str(f,'building'),developer:str(f,'developer'),budget:Number(str(f,'budget'))||0,priority:str(f,'priority') as Priority,ownerStage:role==='Buyer'?'':str(f,'ownerStage'),nextAction:str(f,'nextAction'),signal:contact?.signal||'New contact · needs qualification',optOut:str(f,'contactable')==='Do not contact',nurture:str(f,'contactable')==='Do not contact'?'Off':contact?.nurture||'Off',notes:contact?.notes||[]};saveContact(c);onClose();onSaved?.(c.id);}
 return <Dialog open onOpenChange={v=>!v&&onClose()}><DialogContent className="form-dialog"><DialogHeader><DialogTitle>{contact?'Edit contact':owner?'Add an owner':'New contact'}</DialogTitle><DialogDescription>Keep the person, property and next step together.</DialogDescription></DialogHeader><form onSubmit={submit} className="form-grid"><Field label="Full name"><Input aria-label="Full name" name="name" required autoFocus defaultValue={contact?.name}/></Field><Field label="Relationship"><Picker label="Relationship" name="role" options={[contact?.role||(owner?'Owner':'Buyer'),...['Buyer','Owner','Buyer & owner'].filter(r=>r!==(contact?.role||(owner?'Owner':'Buyer')))]}/></Field><Field label="Email"><Input aria-label="Email" type="email" name="email" defaultValue={contact?.email} placeholder="name@example.com"/></Field><Field label="Phone"><Input aria-label="Phone" type="tel" name="phone" defaultValue={contact?.phone} placeholder="Optional"/></Field><Field label="Lead source"><Picker label="Lead source" name="source" options={[contact?.source||'Manual import',...SOURCES.filter(s=>s!==(contact?.source||'Manual import'))]}/></Field><Field label="Priority"><Picker label="Priority" name="priority" options={[contact?.priority||(owner?'Listing':'Nurture'),...['Closing','Listing','Nurture'].filter(p=>p!==(contact?.priority||(owner?'Listing':'Nurture')))]}/></Field><Field label="Area"><Input aria-label="Area" name="area" defaultValue={contact?.area} placeholder="Dubai Creek Harbour"/></Field><Field label="Building"><Input aria-label="Building" name="building" defaultValue={contact?.building} placeholder="Palace Residences"/></Field><Field label="Developer"><Input aria-label="Developer" name="developer" defaultValue={contact?.developer||'Emaar'}/></Field><Field label="Budget / property value (AED)"><Input aria-label="Budget / property value (AED)" name="budget" type="number" min="0" step="1000" defaultValue={contact?.budget||''}/></Field><Field label="Owner stage"><Picker label="Owner stage" name="ownerStage" options={[contact?.ownerStage||'Cold owner',...OWNER_STAGES.filter(s=>s!==(contact?.ownerStage||'Cold owner'))]}/></Field><Field label="Outreach preference"><Picker label="Outreach preference" name="contactable" options={contact?.optOut?['Do not contact','May contact']:['May contact','Do not contact']}/></Field><div className="col-span-full"><Field label="Next action"><Input aria-label="Next action" name="nextAction" defaultValue={contact?.nextAction} placeholder="Confirm their timeline"/></Field></div><div className="form-actions"><Button type="button" variant="outline" onClick={onClose}>Cancel</Button><Button type="submit">Save contact</Button></div></form></DialogContent></Dialog>;
}
export function DealForm({deal,onClose,onSaved}:{deal?:Deal;onClose:()=>void;onSaved?:(id:string)=>void}){
 const {data,setData,notify}=useCRM();
 function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const contact=data.contacts.find(c=>c.name===str(f,'contact'));if(!contact)return;const d:Deal={id:deal?.id||uid(),name:str(f,'name'),contactId:contact.id,property:str(f,'property'),value:Number(str(f,'value')),stage:str(f,'stage'),closingDate:str(f,'closingDate'),nextAction:str(f,'nextAction'),notes:str(f,'notes'),checklist:deal?.checklist||[{label:'Buyer requirements confirmed',done:false},{label:'Offer agreed',done:false},{label:'Contract signed',done:false},{label:'Transfer completed',done:false}]};setData(s=>({...s,deals:s.deals.some(x=>x.id===d.id)?s.deals.map(x=>x.id===d.id?d:x):[d,...s.deals],contacts:s.contacts.map(c=>c.id===contact.id&&['Offer ready','Negotiating','Under contract'].includes(d.stage)?{...c,priority:'Closing'}:c),activities:[{id:uid(),contactId:contact.id,text:`Deal ${deal?'updated':'created'}: ${d.name} · ${d.stage}.`,kind:'system',at:new Date().toISOString()},...s.activities]}));notify('Deal saved');onClose();onSaved?.(d.id);}
 const contact=data.contacts.find(c=>c.id===deal?.contactId)?.name||data.contacts[0]?.name;
 return <Dialog open onOpenChange={v=>!v&&onClose()}><DialogContent className="form-dialog"><DialogHeader><DialogTitle>{deal?'Edit deal':'New deal'}</DialogTitle><DialogDescription>Track a property opportunity from qualification to closing.</DialogDescription></DialogHeader><form onSubmit={submit} className="form-grid"><Field label="Deal name"><Input aria-label="Deal name" name="name" defaultValue={deal?.name} required/></Field><Field label="Contact"><Picker label="Deal contact" name="contact" options={[contact,...data.contacts.map(c=>c.name).filter(n=>n!==contact)]}/></Field><Field label="Property"><Input aria-label="Property" name="property" required defaultValue={deal?.property}/></Field><Field label="Value (AED)"><Input aria-label="Value (AED)" name="value" type="number" min="0" required defaultValue={deal?.value}/></Field><Field label="Stage"><Picker label="Deal stage" name="stage" options={[deal?.stage||'Qualified',...DEAL_STAGES.filter(s=>s!==(deal?.stage||'Qualified'))]}/></Field><Field label="Target closing date"><Input aria-label="Target closing date" type="date" name="closingDate" required defaultValue={deal?.closingDate||shiftDate(30)}/></Field><div className="col-span-full"><Field label="Next step"><Input aria-label="Next step" name="nextAction" defaultValue={deal?.nextAction}/></Field></div><div className="col-span-full"><Field label="Deal notes"><Textarea aria-label="Deal notes" name="notes" defaultValue={deal?.notes}/></Field></div><div className="form-actions"><Button type="button" variant="outline" onClick={onClose}>Cancel</Button><Button type="submit">Save deal</Button></div></form></DialogContent></Dialog>;
}
export function TaskForm({task,contactId,onClose}:{task?:Task;contactId?:string;onClose:()=>void}){const{data,setData,notify}=useCRM();function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const contact=data.contacts.find(c=>c.name===str(f,'contact'));const t:Task={id:task?.id||uid(),title:str(f,'title'),contactId:contact?.id||'',priority:str(f,'priority') as Priority,due:str(f,'due'),time:str(f,'time'),done:task?.done||false};setData(s=>({...s,tasks:task?s.tasks.map(x=>x.id===task.id?t:x):[...s.tasks,t]}));notify('Reminder saved');onClose();}const selected=data.contacts.find(c=>c.id===(task?.contactId||contactId))?.name||'No contact';return <Dialog open onOpenChange={v=>!v&&onClose()}><DialogContent><DialogHeader><DialogTitle>{task?'Edit reminder':'New task'}</DialogTitle><DialogDescription>Times are in Dubai (GST). Reminders appear in your daily queue.</DialogDescription></DialogHeader><form className="form-grid" onSubmit={submit}><div className="col-span-full"><Field label="Task"><Input aria-label="Task" name="title" required defaultValue={task?.title}/></Field></div><Field label="Contact"><Picker label="Task contact" name="contact" options={[selected,...['No contact',...data.contacts.map(c=>c.name)].filter(n=>n!==selected)]}/></Field><Field label="Priority"><Picker label="Task priority" name="priority" options={[task?.priority||'Nurture',...['Closing','Listing','Nurture'].filter(p=>p!==(task?.priority||'Nurture'))]}/></Field><Field label="Due date"><Input aria-label="Due date" type="date" name="due" required defaultValue={task?.due||today()}/></Field><Field label="Time"><Input aria-label="Time" type="time" name="time" required defaultValue={task?.time||'10:00'}/></Field><p className="text-sm text-muted-foreground col-span-full">Linked contacts use their current CRM priority.</p><div className="form-actions"><Button type="button" variant="outline" onClick={onClose}>Cancel</Button><Button type="submit">Save reminder</Button></div></form></DialogContent></Dialog>;}
