'use client';
import Link from 'next/link';
import {useState} from 'react';
import {ArrowRight,Building2,Check,Handshake,ChevronRight} from "@/components/icons";
import {Flame} from "lucide-react";
import {Button} from '@/components/ui/button';
import {Card,CardContent} from '@/components/ui/card';
import {Table,TableBody,TableCell,TableHead,TableHeader,TableRow} from '@/components/ui/table';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {useCRM} from '@/components/crm-provider';
import {CheckButton,Empty,Metric,Picker,Pill,PriorityPill,SearchInput} from '@/components/crm-ui';
import {useTableSort,SortHead} from '@/components/sortable-table';
import {TaskForm} from '@/components/forms';
import {Task,OWNER_STAGES,DEAL_STAGES,SOURCES,money,orderedTasks,today,priorityFor,ranks} from '@/lib/model';
type ContactAction={onContact:(id:string)=>void};type DealAction={onDeal:(id:string)=>void};
export function TaskRow({task,onContact,compact=false}:{task:Task;compact?:boolean}&ContactAction){const{data,setData,notify}=useCRM();const c=data.contacts.find(c=>c.id===task.contactId);return <div className={`task-row ${task.done?'task-done':''}`}><CheckButton checked={task.done} label={`${task.done?'Reopen':'Complete'} ${task.title}`} onClick={()=>{setData(s=>({...s,tasks:s.tasks.map(t=>t.id===task.id?{...t,done:!t.done}:t)}));notify(task.done?'Task reopened':'Task completed');}}/><div className="task-info"><Button variant="link" onClick={()=>c&&onContact(c.id)} className="text-link" disabled={!c}>{task.title}</Button><p>{c?.building||'Workspace task'}{!compact&&c&&` · ${c.name}`}</p></div><div className="task-meta"><PriorityPill priority={priorityFor(task,data.contacts)}/><span className={task.due<today()&&!task.done?'overdue':''}>{task.due<today()?'Overdue':task.due===today()?task.time:task.due.slice(5)}</span></div>{c&&<Button className="row-chevron" variant="ghost" size="icon-sm" aria-label={`Open ${c.name}`} onClick={()=>onContact(c.id)}><ChevronRight/></Button>}</div>;}
export function TodayView({onContact}:ContactAction&DealAction){
 const{data,setData,notify}=useCRM();
 const closing=data.contacts.filter(c=>c.priority==='Closing');
 const owners=data.contacts.filter(c=>c.role!=='Buyer'&&!['Lost','Listing won'].includes(c.ownerStage));
 const pending=data.approvals.filter(a=>a.status==='Pending');
 const tasks=orderedTasks(data.tasks.filter(t=>!t.done&&t.due<=today()),data.contacts);
 const active=data.deals.filter(d=>!d.stage.startsWith('Closed'));
 function complete(id:string){setData(s=>({...s,tasks:s.tasks.map(t=>t.id===id?{...t,done:true}:t)}));notify('Task completed');}
 return <>
  <div className="metrics-grid three dashboard-metrics"><Metric label="Ready to close" value={closing.length}/><Metric label="Owners in progress" value={owners.length}/><Metric label="Active deal value" value={money(active.reduce((s,d)=>s+d.value,0),true)}/></div>
  <section className="flat-section"><div className="section-heading"><div><h2>Daily priorities</h2><p>Closing buyers first, then listings and nurture.</p></div><Link href="/tasks/" className="section-link">All tasks <ArrowRight size={15}/></Link></div>
   <div className="table-frame daily-priorities-table"><Table><TableHeader><TableRow><TableHead className="check-cell"><span className="sr-only">Complete</span></TableHead><TableHead>Next action</TableHead><TableHead>Contact</TableHead><TableHead>Priority</TableHead><TableHead>Due</TableHead></TableRow></TableHeader><TableBody>{tasks.slice(0,5).map(t=>{const c=data.contacts.find(c=>c.id===t.contactId);return <TableRow key={t.id}><TableCell className="check-cell"><CheckButton checked={false} label={`Complete ${t.title}`} onClick={()=>complete(t.id)}/></TableCell><TableCell><Button variant="link" className="text-link" disabled={!c} onClick={()=>c&&onContact(c.id)}>{t.title}</Button></TableCell><TableCell>{c?.name||'Workspace'}</TableCell><TableCell><PriorityPill priority={priorityFor(t,data.contacts)}/></TableCell><TableCell className={t.due<today()?'overdue':''}>{t.due<today()?'Overdue':t.time}</TableCell></TableRow>;})}</TableBody></Table>{!tasks.length&&<Empty title="All caught up" description="There are no pending tasks for today."/>}</div>
  </section>
  <section className="flat-section"><div className="section-heading"><div><h2>Needs your review</h2><p>Prepared follow-ups and owners ready for a conversation.</p></div><Link href="/assistant/" className="section-link">Open assistant <ArrowRight size={15}/></Link></div><div className="review-preview">{pending.slice(0,3).map(a=><div key={a.id} className="review-preview-row"><div><Button variant="link" className="text-link" onClick={()=>onContact(a.contactId)}>{a.title}</Button><p>{data.contacts.find(c=>c.id===a.contactId)?.name}</p></div><Pill tone={a.kind==='handoff'?'listing':'neutral'}>{a.kind==='handoff'?'Agent handoff':a.kind==='insight'?'Market insight':'Follow-up'}</Pill><Button variant="outline" size="sm" asChild><Link href="/assistant/">Review</Link></Button></div>)}{!pending.length&&<Empty title="Everything reviewed" description="New handoffs and prepared drafts will appear here."/>}</div></section>
 </>;
}
export function ContactsView({onContact}:ContactAction){const{data}=useCRM();const[q,setQ]=useState('');const[role,setRole]=useState('All relationships');const[source,setSource]=useState('All sources');const[priority,setPriority]=useState('All priorities');const filtered=data.contacts.filter(c=>`${c.name} ${c.email} ${c.phone} ${c.area} ${c.building}`.toLowerCase().includes(q.toLowerCase())&&(role==='All relationships'||c.role===role)&&(source==='All sources'||c.source===source)&&(priority==='All priorities'||c.priority===priority));const sorting=useTableSort(filtered,{name:c=>c.name,role:c=>c.role,building:c=>c.building,budget:c=>c.budget,priority:c=>ranks[c.priority],source:c=>c.source});return <><div className="directory"><div className="toolbar"><SearchInput value={q} onChange={setQ}/><Picker label="Filter relationship" value={role} onChange={setRole} options={['All relationships','Buyer','Owner','Buyer & owner']}/><Picker label="Filter source" value={source} onChange={setSource} options={['All sources',...SOURCES]}/><Picker label="Filter priority" value={priority} onChange={setPriority} options={['All priorities','Closing','Listing','Nurture']}/></div><div className="table-frame"><Table><TableHeader><TableRow>{[['Contact','name'],['Relationship','role'],['Property / area','building'],['Budget / value','budget'],['Priority','priority'],['Source','source']].map(([label,key])=><SortHead key={key} column={key} sorting={sorting}>{label}</SortHead>)}</TableRow></TableHeader><TableBody>{sorting.rows.map(c=><TableRow key={c.id} className="record-row" onClick={()=>onContact(c.id)}><TableCell><Button variant="link" className="text-link" onClick={e=>{e.stopPropagation();onContact(c.id);}}>{c.name}</Button></TableCell><TableCell><Pill>{c.role}</Pill></TableCell><TableCell><span>{c.building||'Not set'}</span></TableCell><TableCell className="tabular-nums">{money(c.budget,true)}</TableCell><TableCell><PriorityPill priority={c.priority}/></TableCell><TableCell><span className="source-text">{c.source}</span></TableCell></TableRow>)}</TableBody></Table>{!filtered.length&&<Empty title="No contacts match" description="Try a different search or clear the filters." action={<Button variant="outline" onClick={()=>{setQ('');setRole('All relationships');setSource('All sources');setPriority('All priorities');}}>Clear filters</Button>}/>}</div><div className="table-footer">{filtered.length} of {data.contacts.length} contacts<span>All contacts are fictional demo records</span></div></div></>;}
export function OwnersView({onContact}:ContactAction){const{data}=useCRM();const[q,setQ]=useState('');const[filter,setFilter]=useState('Active pipeline');const owners=data.contacts.filter(c=>c.role!=='Buyer');const filtered=owners.filter(c=>`${c.name} ${c.building}`.toLowerCase().includes(q.toLowerCase())&&(filter==='All stages'||!['Listing won','Lost'].includes(c.ownerStage)));return <><div className="view-heading"><div><h2>Owner relationships</h2><p>{owners.length} owners · {owners.filter(c=>c.nurture==='Active').length} in nurture · {owners.filter(c=>c.ownerStage==='Listing won').length} listing won</p></div></div><div className="toolbar"><SearchInput value={q} onChange={setQ} placeholder="Search owners…"/><Picker label="Owner pipeline filter" value={filter} onChange={setFilter} options={['Active pipeline','All stages']}/><span className="muted text-sm">Open a card to move its stage</span></div><div className="kanban-scroll" role="region" aria-label="Owner stages, scroll horizontally" tabIndex={0}><div className="kanban-board">{OWNER_STAGES.filter(s=>filter==='All stages'||!['Listing won','Lost'].includes(s)).map((stage,i)=><section className="kanban-column" key={stage}><div className="kanban-heading"><span className={`stage-dot stage-${i}`}/><h3>{stage}</h3><span>{filtered.filter(c=>c.ownerStage===stage).length}</span></div>{filtered.filter(c=>c.ownerStage===stage).map(c=><Card key={c.id} className="owner-card"><CardContent><Button variant="ghost" className="owner-name" onClick={()=>onContact(c.id)}>{c.name}</Button><p className="property-line"><Building2 size={14}/>{c.building}</p><strong className="owner-value">{money(c.budget,true)}</strong><p className="signal"><span/>{c.signal}</p><div className="owner-bottom"><Pill tone={c.nurture==='Paused'?'listing':'nurture'}>{c.nurture==='Paused'?'Agent follow-up':c.nurture==='Active'?'Nurturing':'Not enrolled'}</Pill><Button variant="ghost" size="icon-sm" aria-label={`Open owner ${c.name}`} onClick={()=>onContact(c.id)}><ChevronRight/></Button></div></CardContent></Card>)}{!filtered.some(c=>c.ownerStage===stage)&&<div className="kanban-empty">No owners here yet</div>}</section>)}</div></div></>;}
export function DealsView({onDeal}:DealAction){const{data}=useCRM();const[q,setQ]=useState('');const[stage,setStage]=useState('All stages');const active=data.deals.filter(d=>!d.stage.startsWith('Closed'));const filtered=data.deals.filter(d=>`${d.name} ${d.property} ${data.contacts.find(c=>c.id===d.contactId)?.name}`.toLowerCase().includes(q.toLowerCase())&&(stage==='All stages'||d.stage===stage));const sorting=useTableSort(filtered,{name:d=>d.name,client:d=>data.contacts.find(c=>c.id===d.contactId)?.name,value:d=>d.value,stage:d=>d.stage,closingDate:d=>d.closingDate,nextAction:d=>d.nextAction});return <><div className="metrics-grid three"><Metric label="Active pipeline" value={money(active.reduce((s,d)=>s+d.value,0),true)} hint={`${active.length} open deals`} icon={<Handshake/>}/><Metric label="Offers & negotiation" value={active.filter(d=>['Offer ready','Negotiating'].includes(d.stage)).length} hint="The highest-value conversations today" icon={<Flame/>} tone="closing"/><Metric label="Closed won" value={money(data.deals.filter(d=>d.stage==='Closed won').reduce((s,d)=>s+d.value,0),true)} hint="Completed demo deal volume" icon={<Check/>} tone="nurture"/></div><div className="directory"><div className="toolbar"><SearchInput value={q} onChange={setQ} placeholder="Search deals…"/><Picker label="Filter deal stage" value={stage} onChange={setStage} options={['All stages',...DEAL_STAGES]}/></div><div className="table-frame"><Table><TableHeader><TableRow>{[['Deal','name'],['Client','client'],['Value','value'],['Stage','stage'],['Closing date','closingDate'],['Next step','nextAction']].map(([label,key])=><SortHead key={key} column={key} sorting={sorting}>{label}</SortHead>)}</TableRow></TableHeader><TableBody>{sorting.rows.map(d=><TableRow key={d.id} className="record-row" onClick={()=>onDeal(d.id)}><TableCell><Button variant="link" className="text-link" onClick={e=>{e.stopPropagation();onDeal(d.id);}}>{d.name}</Button></TableCell><TableCell>{data.contacts.find(c=>c.id===d.contactId)?.name}</TableCell><TableCell>{money(d.value,true)}</TableCell><TableCell><Pill tone={d.stage==='Closed won'?'nurture':['Offer ready','Negotiating'].includes(d.stage)?'closing':'neutral'}>{d.stage}</Pill></TableCell><TableCell>{new Date(d.closingDate+'T12:00:00').toLocaleDateString('en-GB',{day:'numeric',month:'short',year:'numeric'})}</TableCell><TableCell className="next-action-cell">{d.nextAction}</TableCell></TableRow>)}</TableBody></Table>{!filtered.length&&<Empty title="No deals match" description="Change the stage or search to see your opportunities."/>}</div><div className="table-footer">{filtered.length} deals<span>Values in AED · commission not included</span></div></div></>;}
export function TasksView({onContact}:ContactAction){const{data}=useCRM();const[filter,setFilter]=useState('Today');const[editing,setEditing]=useState<Task|null>(null);const tasks=orderedTasks(data.tasks.filter(t=>filter==='Completed'?t.done:!t.done&&(filter==='All upcoming'||filter==='Overdue'&&t.due<today()||filter==='Today'&&t.due<=today())),data.contacts);return <><div className="view-heading"><div><h2>Your daily priorities</h2><p>Closing buyers → listing opportunities → ongoing nurture. Dubai time.</p></div><Pill>{data.tasks.filter(t=>!t.done).length} open</Pill></div><Tabs value={filter} onValueChange={setFilter}><TabsList>{['Today','Overdue','All upcoming','Completed'].map(t=><TabsTrigger key={t} value={t}>{t}</TabsTrigger>)}</TabsList></Tabs><Card><CardContent className="task-directory">{tasks.length?tasks.map(t=><div key={t.id} className="task-edit-row"><TaskRow task={t} onContact={onContact}/><Button variant="ghost" size="sm" onClick={()=>setEditing(t)}>Edit</Button></div>):<Empty title="Nothing on this list" description="Add a task or switch to another view."/>}</CardContent></Card>{editing&&<TaskForm task={editing} onClose={()=>setEditing(null)}/>}</>;}
