'use client';
import Link from 'next/link';
import {useEffect,useState} from 'react';
import {LayoutDashboard,Users,Building2,Handshake,ListTodo,Megaphone,Sparkles,ChartNoAxesCombined,Search,Bell,Plus,PanelLeft,ArrowUpRight,ChevronRight,Command,Orbit} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Sheet,SheetContent,SheetHeader,SheetTitle,SheetDescription} from '@/components/ui/sheet';
import {useCRM} from '@/components/crm-provider';
import {DemoNote,Avatar,SearchInput,PriorityPill,Empty} from '@/components/crm-ui';
import {ContactForm,DealForm,TaskForm} from '@/components/forms';
import {TodayView,ContactsView,OwnersView,DealsView,TasksView} from '@/components/main-views';
import {CampaignsView,AssistantView,InsightsView,SettingsView} from '@/components/growth-views';
import {ContactDetail,DealDetail} from '@/components/details';
import {orderedTasks,today} from '@/lib/model';
const nav=[{id:'today',label:'Overview',icon:LayoutDashboard},{id:'contacts',label:'Contacts',icon:Users},{id:'owners',label:'Owner pipeline',icon:Building2},{id:'deals',label:'Deals',icon:Handshake},{id:'tasks',label:'Tasks & reminders',icon:ListTodo},{id:'campaigns',label:'Campaigns',icon:Megaphone},{id:'assistant',label:'AI assistant',icon:Sparkles},{id:'insights',label:'Market insights',icon:ChartNoAxesCombined}];
export function Workspace({view}:{view:string}){
 const{data,storageError}=useCRM();const[mobile,setMobile]=useState(false);const[search,setSearch]=useState(false);const[query,setQuery]=useState('');const[notifications,setNotifications]=useState(false);const[form,setForm]=useState('');const[contactId,setContactId]=useState('');const[dealId,setDealId]=useState('');
 const pending=data.approvals.filter(a=>a.status==='Pending').length;const due=orderedTasks(data.tasks.filter(t=>!t.done&&t.due<=today()),data.contacts);
 const title=view==='today'?'Overview':view==='settings'?'Workspace settings':nav.find(n=>n.id===view)?.label||'Overview';
 useEffect(()=>{const event=(e:KeyboardEvent)=>{if((e.metaKey||e.ctrlKey)&&e.key==='k'){e.preventDefault();setSearch(v=>!v);}};window.addEventListener('keydown',event);const params=new URLSearchParams(window.location.search);if(params.get('contact'))setTimeout(()=>setContactId(params.get('contact')||''),0);if(params.get('deal'))setTimeout(()=>setDealId(params.get('deal')||''),0);return()=>window.removeEventListener('keydown',event);},[]);
 const openContact=(id:string)=>{setDealId('');setContactId(id);};const openDeal=(id:string)=>{setContactId('');setDealId(id);};
 const navigation=<><Link href="/" className="brand"><span className="brand-mark"><Orbit size={24}/></span><span>Broker<span className="brand-os">OS</span></span></Link><div className="workspace-switch"><span className="workspace-icon">W</span><div>Walid’s workspace<small>Dubai · Independent agent</small></div></div><p className="nav-label">WORKSPACE</p><nav aria-label="Main navigation">{nav.map((n,i)=><Link key={n.id} href={n.id==='today'?'/':`/${n.id}/`} className={`nav-link ${view===n.id?'active':''} ${i===5?'nav-break':''}`} onClick={()=>setMobile(false)} aria-current={view===n.id?'page':undefined}><n.icon size={18}/><span>{n.label}</span>{n.id==='assistant'&&pending>0&&<span className="nav-count">{pending}</span>}</Link>)}</nav><div className="sidebar-bottom"><div className="demo-box"><span className="demo-dot"/>Interactive demo<small>Your changes stay in this browser.</small></div><Link href="/settings/" className="profile" aria-label="Profile and workspace settings"><Avatar name="Walid Naim" small/><div>Walid Naim<small>Real estate agent</small></div><ChevronRight size={15}/></Link></div></>;
 const action=view==='deals'?'New deal':view==='tasks'||view==='today'?'Add task':view==='owners'?'Add owner':'Add contact';
 return <div className="app-shell"><aside className="sidebar">{navigation}</aside><Sheet open={mobile} onOpenChange={setMobile}><SheetContent side="left" className="mobile-nav"><SheetHeader className="sr-only"><SheetTitle>Navigation</SheetTitle><SheetDescription>BrokerOS workspace pages</SheetDescription></SheetHeader>{navigation}</SheetContent></Sheet><div className="main-shell"><header className="topbar"><div className="topbar-title"><Button variant="ghost" size="icon" aria-label="Open navigation" className="mobile-toggle" onClick={()=>setMobile(true)}><PanelLeft/></Button><h1>{title}</h1></div><div className="topbar-actions"><Button variant="ghost" className="global-search" onClick={()=>setSearch(true)} aria-label="Search workspace"><Search/><span>Search anything</span><kbd>⌘ K</kbd></Button><Button size="icon" variant="ghost" className="notification-button" aria-label="Priority notifications" onClick={()=>setNotifications(true)}><Bell/>{due.length>0&&<span/>}</Button>{!['campaigns','assistant','insights','settings'].includes(view)&&<Button onClick={()=>setForm(view==='deals'?'deal':view==='today'||view==='tasks'?'task':view==='owners'?'owner':'contact')}><Plus/><span className="action-label">{action}</span></Button>}</div></header><main className="page-shell">{storageError&&<p role="alert" className="storage-warning">Browser storage is unavailable. Changes will last only for this session.</p>}{view==='today'&&<TodayView onContact={openContact} onDeal={openDeal}/ >}{view==='contacts'&&<ContactsView onContact={openContact}/ >}{view==='owners'&&<OwnersView onContact={openContact}/ >}{view==='deals'&&<DealsView onDeal={openDeal}/ >}{view==='tasks'&&<TasksView onContact={openContact}/ >}{view==='campaigns'&&<CampaignsView onContact={openContact}/ >}{view==='assistant'&&<AssistantView onContact={openContact}/ >}{view==='insights'&&<InsightsView/ >}{view==='settings'&&<SettingsView/ >}<DemoNote/></main></div>
 <Dialog open={search} onOpenChange={setSearch}><DialogContent className="search-dialog"><DialogHeader><DialogTitle>Search your workspace</DialogTitle><DialogDescription>Find a contact, property, source or deal.</DialogDescription></DialogHeader><SearchInput value={query} onChange={setQuery} placeholder="Search names, properties, deals…"/><div className="search-results">{data.contacts.filter(c=>`${c.name} ${c.building} ${c.email} ${c.source}`.toLowerCase().includes(query.toLowerCase())).slice(0,6).map(c=><Button variant="ghost" className="search-result" key={c.id} onClick={()=>{setSearch(false);openContact(c.id);}}><Avatar name={c.name} small/><span>{c.name}<small>{c.building} · {c.role}</small></span><ArrowUpRight/></Button>)}{query&&data.deals.filter(d=>`${d.name} ${d.property}`.toLowerCase().includes(query.toLowerCase())).slice(0,4).map(d=><Button variant="ghost" className="search-result" key={d.id} onClick={()=>{setSearch(false);openDeal(d.id);}}><Handshake size={20}/><span>{d.name}<small>{d.property} · {d.stage}</small></span><ArrowUpRight/></Button>)}{!data.contacts.some(c=>`${c.name} ${c.building} ${c.email} ${c.source}`.toLowerCase().includes(query.toLowerCase()))&&!data.deals.some(d=>`${d.name} ${d.property}`.toLowerCase().includes(query.toLowerCase()))&&<Empty title="No matches" description="Try a name, source or building."/>}</div><div className="search-tip"><Command size={14}/> K to open · Esc to close</div></DialogContent></Dialog>
 <Sheet open={notifications} onOpenChange={setNotifications}><SheetContent className="detail-sheet"><SheetHeader><SheetTitle>Needs your attention</SheetTitle><SheetDescription>Closing first. Then listings. Then nurture.</SheetDescription></SheetHeader><div className="detail-body"><p className="text-sm text-muted-foreground">In-app reminders · Dubai time</p>{due.length===0?<Empty title="You’re all caught up" description="New reminders will appear here."/>:due.map(t=><div className="notification-item" key={t.id}><PriorityPill priority={data.contacts.find(c=>c.id===t.contactId)?.priority||t.priority}/><h3>{t.title}</h3><p>{t.due<today()?'Overdue':`Today · ${t.time}`}</p><Button variant="outline" size="sm" onClick={()=>{setNotifications(false);if(t.contactId)openContact(t.contactId);else setForm('task');}}>Review <ChevronRight/></Button></div>)}</div></SheetContent></Sheet>
 {form==='contact'||form==='owner'?<ContactForm owner={form==='owner'} onClose={()=>setForm('')} onSaved={openContact}/>:form==='deal'?<DealForm onClose={()=>setForm('')} onSaved={openDeal}/>:form==='task'?<TaskForm onClose={()=>setForm('')}/>:null}
 {contactId&&<ContactDetail id={contactId} onClose={()=>setContactId('')} onDeal={openDeal}/>}{dealId&&<DealDetail id={dealId} onClose={()=>setDealId('')} onContact={openContact}/>}
 </div>;
}
